# Generated by Django 3.2.4 on 2021-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.CharField(default='', max_length=1000)),
                ('subtitles', models.CharField(max_length=100000)),
            ],
        ),
    ]
