# Generated by Django 3.2.4 on 2021-06-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='video_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
